//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloEquipos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAO_Equipo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAO_Equipo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloEquipos.RecursoDAO_Equipo" +
                            "", typeof(RecursoDAO_Equipo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eq_categoria.
        /// </summary>
        internal static string eq_categoria {
            get {
                return ResourceManager.GetString("eq_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eq_cliente.
        /// </summary>
        internal static string eq_cliente {
            get {
                return ResourceManager.GetString("eq_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eq_estatus.
        /// </summary>
        internal static string eq_estatus {
            get {
                return ResourceManager.GetString("eq_estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eq_marca.
        /// </summary>
        internal static string eq_marca {
            get {
                return ResourceManager.GetString("eq_marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eq_modelo.
        /// </summary>
        internal static string eq_modelo {
            get {
                return ResourceManager.GetString("eq_modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eq_numequipo.
        /// </summary>
        internal static string eq_numequipo {
            get {
                return ResourceManager.GetString("eq_numequipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eq_serial.
        /// </summary>
        internal static string eq_serial {
            get {
                return ResourceManager.GetString("eq_serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREGAR_EQUIPO.
        /// </summary>
        internal static string ProcedimientoAgregarEquipo {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASIGNAR_EQUIPO.
        /// </summary>
        internal static string ProcedimientoAsignarEquipo {
            get {
                return ResourceManager.GetString("ProcedimientoAsignarEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EQUIPO_NUM.
        /// </summary>
        internal static string ProcedimientoConsultarEquipoNumero {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarEquipoNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EQUIPO_SERIAL.
        /// </summary>
        internal static string ProcedimientoConsultarEquipoSerial {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarEquipoSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EQUIPOS_LIBRES.
        /// </summary>
        internal static string ProcedimientoConsultarEquiposLibres {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarEquiposLibres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EQUIPOS_TODOS.
        /// </summary>
        internal static string ProcedimientoConsultarTodosEquipos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarTodosEquipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR_EQUIPO.
        /// </summary>
        internal static string ProcedimientoEliminarEquipo {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_EQUIPO.
        /// </summary>
        internal static string ProcedimientoModificarEquipo {
            get {
                return ResourceManager.GetString("ProcedimientoModificarEquipo", resourceCulture);
            }
        }
    }
}
