//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSC_Servicios_Corporativos.Modelo.Comun {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoMail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoMail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPSC_Servicios_Corporativos.Modelo.Comun.RecursoMail", typeof(RecursoMail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de confirmación.
        /// </summary>
        internal static string Cabecera {
            get {
                return ResourceManager.GetString("Cabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Equipo. .
        /// </summary>
        internal static string CabeceraSolicitud {
            get {
                return ResourceManager.GetString("CabeceraSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soporte@hp-sc.net.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su código de confirmación es:  .
        /// </summary>
        internal static string Cuerpo {
            get {
                return ResourceManager.GetString("Cuerpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ha solicitado el siguiente equipo:.
        /// </summary>
        internal static string CuerpoSolicitudP1 {
            get {
                return ResourceManager.GetString("CuerpoSolicitudP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La persona de contacto que ofrece el cliente es el siguiente.
        /// </summary>
        internal static string CuerpoSolicitudP2 {
            get {
                return ResourceManager.GetString("CuerpoSolicitudP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th34v3ng3r$.
        /// </summary>
        internal static string PWD {
            get {
                return ResourceManager.GetString("PWD", resourceCulture);
            }
        }
    }
}
