//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloUsuarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAO_Usuario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAO_Usuario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloUsuarios.RecursoDAO_Usuar" +
                            "io", typeof(RecursoDAO_Usuario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @emp_apellido.
        /// </summary>
        internal static string emp_apellido {
            get {
                return ResourceManager.GetString("emp_apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @emp_password.
        /// </summary>
        internal static string emp_contrasena {
            get {
                return ResourceManager.GetString("emp_contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @emp_correo.
        /// </summary>
        internal static string emp_correo {
            get {
                return ResourceManager.GetString("emp_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @emp_nombre.
        /// </summary>
        internal static string emp_nombre {
            get {
                return ResourceManager.GetString("emp_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @emp_rol.
        /// </summary>
        internal static string emp_rol {
            get {
                return ResourceManager.GetString("emp_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @emp_usuario.
        /// </summary>
        internal static string emp_usuario {
            get {
                return ResourceManager.GetString("emp_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREGAR_EMPLEADO.
        /// </summary>
        internal static string ProcedimientoAgregarEmpleado {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREGAR_ROL_EMPLEADO.
        /// </summary>
        internal static string ProcedimientoAgregarRolEmpleado {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarRolEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBIAR_PWD_EMPLEADO.
        /// </summary>
        internal static string ProcedimientoCambiarPwdEmpleado {
            get {
                return ResourceManager.GetString("ProcedimientoCambiarPwdEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EMPLEADO.
        /// </summary>
        internal static string ProcedimientoConsultarEmpleado {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EMPLEADO_CORREO.
        /// </summary>
        internal static string ProcedimientoConsultarEmpleadoCorreo {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarEmpleadoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EMPLEADOS.
        /// </summary>
        internal static string ProcedimientoConsultarEmpleados {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_ROLES.
        /// </summary>
        internal static string ProcedimientoConsultarRoles {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR_EMPLEADO.
        /// </summary>
        internal static string ProcedimientoEliminarEmpleado {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_EMPLEADO.
        /// </summary>
        internal static string ProcedimientoModificarEmpleado {
            get {
                return ResourceManager.GetString("ProcedimientoModificarEmpleado", resourceCulture);
            }
        }
    }
}
