//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloClientes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAO_Cliente {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAO_Cliente() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloClientes.RecursoDAO_Clien" +
                            "te", typeof(RecursoDAO_Cliente).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cli_correo.
        /// </summary>
        internal static string cli_correo {
            get {
                return ResourceManager.GetString("cli_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cli_direccion.
        /// </summary>
        internal static string cli_direccion {
            get {
                return ResourceManager.GetString("cli_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cli_nombre.
        /// </summary>
        internal static string cli_nombre {
            get {
                return ResourceManager.GetString("cli_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cli_password.
        /// </summary>
        internal static string cli_password {
            get {
                return ResourceManager.GetString("cli_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cli_usuario.
        /// </summary>
        internal static string cli_usuario {
            get {
                return ResourceManager.GetString("cli_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREGAR_CLIENTE.
        /// </summary>
        internal static string ProcedimientoAgregarCliente {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBIAR_PWD_CLIENTE.
        /// </summary>
        internal static string ProcedimientoCambiarPwdCliente {
            get {
                return ResourceManager.GetString("ProcedimientoCambiarPwdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EQUIPO_CONTRATO.
        /// </summary>
        internal static string ProcedimientoConsultaEquiposContrato {
            get {
                return ResourceManager.GetString("ProcedimientoConsultaEquiposContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_CLIENTE.
        /// </summary>
        internal static string ProcedimientoConsultarCliente {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_CLIENTE_CORREO.
        /// </summary>
        internal static string ProcedimientoConsultarClienteCorreo {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarClienteCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_CLIENTES.
        /// </summary>
        internal static string ProcedimientoConsultarClientes {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_CONTRATOS_CLIENTE.
        /// </summary>
        internal static string ProcedimientoConsultarContratos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarContratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EQUIPOS_CLIENTE.
        /// </summary>
        internal static string ProcedimientoConsultarEquipos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarEquipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_SERVICIO_CONTRATO.
        /// </summary>
        internal static string ProcedimientoConsultaServiciosContrato {
            get {
                return ResourceManager.GetString("ProcedimientoConsultaServiciosContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR_CLIENTE.
        /// </summary>
        internal static string ProcedimientoEliminarCliente {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_CLIENTE.
        /// </summary>
        internal static string ProcedimientoModificarCliente {
            get {
                return ResourceManager.GetString("ProcedimientoModificarCliente", resourceCulture);
            }
        }
    }
}
