//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloServicios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAO_Servicio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAO_Servicio() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloServicios.RecursoDAO_Serv" +
                            "icio", typeof(RecursoDAO_Servicio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eqsv_contrato.
        /// </summary>
        internal static string eqsv_contrato {
            get {
                return ResourceManager.GetString("eqsv_contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eqsv_fechafin.
        /// </summary>
        internal static string eqsv_fechafin {
            get {
                return ResourceManager.GetString("eqsv_fechafin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eqsv_fechaini.
        /// </summary>
        internal static string eqsv_fechaini {
            get {
                return ResourceManager.GetString("eqsv_fechaini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eqsv_id.
        /// </summary>
        internal static string eqsv_id {
            get {
                return ResourceManager.GetString("eqsv_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREGAR_SERVICIO.
        /// </summary>
        internal static string ProcedimientoAgregarServicio {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASIGNAR_SERVICIO.
        /// </summary>
        internal static string ProcedimientoAsignarServicio {
            get {
                return ResourceManager.GetString("ProcedimientoAsignarServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_SERVICIO.
        /// </summary>
        internal static string ProcedimientoConsultarServicio {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_SERVICIO_ASIGNADO.
        /// </summary>
        internal static string ProcedimientoConsultarServicioAsignado {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarServicioAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_SERVICIOS.
        /// </summary>
        internal static string ProcedimientoConsultarServicios {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR_SERVICIO.
        /// </summary>
        internal static string ProcedimientoEliminarServicio {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR_SERVICIO_ASIGNADO.
        /// </summary>
        internal static string ProcedimientoEliminarServicioAsignado {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarServicioAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_SERVICIO.
        /// </summary>
        internal static string ProcedimientoModificarServicio {
            get {
                return ResourceManager.GetString("ProcedimientoModificarServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_SERVICIO_ASIGNADO.
        /// </summary>
        internal static string ProcedimientoModificarServicioAsignado {
            get {
                return ResourceManager.GetString("ProcedimientoModificarServicioAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_SERVICIOS_POR_EQUIPO.
        /// </summary>
        internal static string ProcediminetoConsultarEquiposServicio {
            get {
                return ResourceManager.GetString("ProcediminetoConsultarEquiposServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @sv_cantdias.
        /// </summary>
        internal static string sv_cantdias {
            get {
                return ResourceManager.GetString("sv_cantdias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @sv_canthoras.
        /// </summary>
        internal static string sv_canthoras {
            get {
                return ResourceManager.GetString("sv_canthoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @sv_disponibilidad.
        /// </summary>
        internal static string sv_disponibilidad {
            get {
                return ResourceManager.GetString("sv_disponibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @sv_feriados.
        /// </summary>
        internal static string sv_feriados {
            get {
                return ResourceManager.GetString("sv_feriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @sv_id.
        /// </summary>
        internal static string sv_id {
            get {
                return ResourceManager.GetString("sv_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @sv_nivelserv.
        /// </summary>
        internal static string sv_nivelserv {
            get {
                return ResourceManager.GetString("sv_nivelserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @sv_tiemporesp.
        /// </summary>
        internal static string sv_tiemporesp {
            get {
                return ResourceManager.GetString("sv_tiemporesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @sv_tiposerv.
        /// </summary>
        internal static string sv_tiposerv {
            get {
                return ResourceManager.GetString("sv_tiposerv", resourceCulture);
            }
        }
    }
}
