//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloPersonaContacto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAO_PersonaContacto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAO_PersonaContacto() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloPersonaContacto.RecursoDA" +
                            "O_PersonaContacto", typeof(RecursoDAO_PersonaContacto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cli_correo.
        /// </summary>
        internal static string cli_correo {
            get {
                return ResourceManager.GetString("cli_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pc_apellido.
        /// </summary>
        internal static string pc_apellido {
            get {
                return ResourceManager.GetString("pc_apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pc_correo.
        /// </summary>
        internal static string pc_correo {
            get {
                return ResourceManager.GetString("pc_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pc_correonuevo.
        /// </summary>
        internal static string pc_correonuevo {
            get {
                return ResourceManager.GetString("pc_correonuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pc_correoviejo.
        /// </summary>
        internal static string pc_correoviejo {
            get {
                return ResourceManager.GetString("pc_correoviejo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pc_estatus.
        /// </summary>
        internal static string pc_estatus {
            get {
                return ResourceManager.GetString("pc_estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pc_nombre.
        /// </summary>
        internal static string pc_nombre {
            get {
                return ResourceManager.GetString("pc_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pc_telflocal.
        /// </summary>
        internal static string pc_telflocal {
            get {
                return ResourceManager.GetString("pc_telflocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pc_telfmovil.
        /// </summary>
        internal static string pc_telfmovil {
            get {
                return ResourceManager.GetString("pc_telfmovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREGAR_PERSONA_CONTACTO.
        /// </summary>
        internal static string ProcedimientoAgregarPersonaContacto {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarPersonaContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_PERSONA_CONTACTO.
        /// </summary>
        internal static string ProcedimientoConsultarPersonaContacto {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarPersonaContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_PERSONAS_CONTACTO.
        /// </summary>
        internal static string ProcedimientoConsultarPersonasContacto {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarPersonasContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_TODOS_CONTACTOS.
        /// </summary>
        internal static string ProcedimientoConsultarTodasPersonas {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarTodasPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR_PERSONA_CONTACTO.
        /// </summary>
        internal static string ProcedimientoEliminarPersonaContacto {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarPersonaContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_PERSONA_CONTACTO.
        /// </summary>
        internal static string ProcedimientoModificarPersonaContacto {
            get {
                return ResourceManager.GetString("ProcedimientoModificarPersonaContacto", resourceCulture);
            }
        }
    }
}
