//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloProductos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAO_Producto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAO_Producto() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloProductos.RecursoDAO_Prod" +
                            "ucto", typeof(RecursoDAO_Producto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pr_categoria.
        /// </summary>
        internal static string pr_categoria {
            get {
                return ResourceManager.GetString("pr_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pr_marca.
        /// </summary>
        internal static string pr_marca {
            get {
                return ResourceManager.GetString("pr_marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pr_modelo.
        /// </summary>
        internal static string pr_modelo {
            get {
                return ResourceManager.GetString("pr_modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pr_numproducto.
        /// </summary>
        internal static string pr_numproducto {
            get {
                return ResourceManager.GetString("pr_numproducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pr_numproductoviejo.
        /// </summary>
        internal static string pr_numproductoviejo {
            get {
                return ResourceManager.GetString("pr_numproductoviejo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREGAR_PRODUCTO.
        /// </summary>
        internal static string ProcedimientoAgregarProducto {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_MARCAS.
        /// </summary>
        internal static string ProcedimientoConsultarMarcas {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_PRODUCTOS.
        /// </summary>
        internal static string ProcedimientoConsultarProductos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_PRODUCTO.
        /// </summary>
        internal static string ProcedimientoModificarProducto {
            get {
                return ResourceManager.GetString("ProcedimientoModificarProducto", resourceCulture);
            }
        }
    }
}
