//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloAliado {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAO_Aliado {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAO_Aliado() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloAliado.RecursoDAO_Aliado", typeof(RecursoDAO_Aliado).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ali_correo.
        /// </summary>
        internal static string ali_correo {
            get {
                return ResourceManager.GetString("ali_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ali_direccion.
        /// </summary>
        internal static string ali_direccion {
            get {
                return ResourceManager.GetString("ali_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ali_nombre.
        /// </summary>
        internal static string ali_nombre {
            get {
                return ResourceManager.GetString("ali_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ali_password.
        /// </summary>
        internal static string ali_password {
            get {
                return ResourceManager.GetString("ali_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ali_usuario.
        /// </summary>
        internal static string ali_usuario {
            get {
                return ResourceManager.GetString("ali_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREGAR_ALIADO.
        /// </summary>
        internal static string ProcedimientoAgregarAliado {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarAliado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBIAR_PWD_ALIADO.
        /// </summary>
        internal static string ProcedimientoCambiarPwdAliado {
            get {
                return ResourceManager.GetString("ProcedimientoCambiarPwdAliado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EQUIPO_CONTRATO.
        /// </summary>
        internal static string ProcedimientoConsultaEquiposContrato {
            get {
                return ResourceManager.GetString("ProcedimientoConsultaEquiposContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_ALIADO.
        /// </summary>
        internal static string ProcedimientoConsultarAliado {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarAliado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_ALIADO_CORREO.
        /// </summary>
        internal static string ProcedimientoConsultarAliadoCorreo {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarAliadoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_ALIADOS.
        /// </summary>
        internal static string ProcedimientoConsultarAliados {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarAliados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_CONTRATOS_ALIADO.
        /// </summary>
        internal static string ProcedimientoConsultarContratos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarContratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_EQUIPOS_ALIADO.
        /// </summary>
        internal static string ProcedimientoConsultarEquipos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarEquipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_SERVICIO_CONTRATO.
        /// </summary>
        internal static string ProcedimientoConsultaServiciosContrato {
            get {
                return ResourceManager.GetString("ProcedimientoConsultaServiciosContrato", resourceCulture);
            }
        }
    }
}
