ALTER TABLE ALIADO
ADD CONSTRAINT FK_ROL_ALIADO
FOREIGN KEY(A_FK_ROL)
REFERENCES ROL(R_ID) ON DELETE SET NULL;

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_ROL_CLIENTE
FOREIGN KEY(C_FK_ROL)
REFERENCES ROL(R_ID) ON DELETE SET NULL;

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_ROL_EMPLEADO
FOREIGN KEY(E_FK_ROL)
REFERENCES ROL(R_ID) ON DELETE SET NULL;

ALTER TABLE EQUIPO_SERVICIO
ADD CONSTRAINT FK_SERVICIO_EQUIPO
FOREIGN KEY(EC_FK_SERVICIO)
REFERENCES SERVICIO(SV_ID);

ALTER TABLE EQUIPO_SERVICIO
ADD CONSTRAINT FK_EQUIPO_SERVICIO
FOREIGN KEY(EC_FK_EQUIPO)
REFERENCES EQUIPO(EQ_SERIAL) ON UPDATE CASCADE;

ALTER TABLE PERSONAL_CONTACTO
ADD CONSTRAINT FK_CLIENTE_PERSONAL
FOREIGN KEY(PC_FK_CLIENTE)
REFERENCES CLIENTE(C_CORREO) ON DELETE CASCADE;

ALTER TABLE EQUIPO
ADD CONSTRAINT FK_CLIENTE_EQUIPO
FOREIGN KEY(EQ_FK_CLIENTE)
REFERENCES CLIENTE(C_CORREO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EQUIPO
ADD CONSTRAINT FK_EQUIPO_NUMERO
FOREIGN KEY(EQ_FK_NUMEROPRODUCTO)
REFERENCES PRODUCTO(P_NUMEROPRODUCTO) ON UPDATE CASCADE;

ALTER TABLE ACTIVIDAD
ADD CONSTRAINT FK_EMPLEADO_ACTIVIDAD
FOREIGN KEY(AC_FK_EMPLEADO)
REFERENCES EMPLEADO(E_CORREO);

ALTER TABLE ACTIVIDAD
ADD CONSTRAINT FK_INCIDENTE_ACTIVIDAD
FOREIGN KEY(AC_FK_INCIDENTE)
REFERENCES INCIDENTE(I_ID);

ALTER TABLE INCIDENTE
ADD CONSTRAINT FK_INCIDENTE_EQUIPO
FOREIGN KEY(I_FK_EQUIPO)
REFERENCES EQUIPO(EQ_SERIAL) ON UPDATE CASCADE;

ALTER TABLE INCIDENTE
ADD CONSTRAINT FK_INCIDENTE_CLIENTE
FOREIGN KEY(I_FK_CLIENTE)
REFERENCES CLIENTE(C_CORREO);

ALTER TABLE INCIDENTE
ADD CONSTRAINT FK_INCIDENTE_ALIADO
FOREIGN KEY(I_FK_ALIADO)
REFERENCES ALIADO(A_CORREO);

ALTER TABLE INCIDENTE
ADD CONSTRAINT FK_INCIDENTE_EMPLEADO
FOREIGN KEY(I_FK_EMPLEADO)
REFERENCES EMPLEADO(E_CORREO);

ALTER TABLE INCIDENTE
ADD CONSTRAINT FK_INCIDENTE_CONTACTO1
FOREIGN KEY(I_FK_PERSONAL_CONTACTO1)
REFERENCES PERSONAL_CONTACTO(PC_CORREO);

ALTER TABLE INCIDENTE
ADD CONSTRAINT FK_INCIDENTE_CONTACTO2
FOREIGN KEY(I_FK_PERSONAL_CONTACTO2)
REFERENCES PERSONAL_CONTACTO(PC_CORREO);

ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_MARCA_PRODUCTO
FOREIGN KEY(P_FK_MARCA)
REFERENCES MARCA(M_MARCA);