//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloIncidentes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAO_Incidentes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAO_Incidentes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPSC_Servicios_Corporativos.Modelo.Acceso_a_datos.ModuloIncidentes.RecursoDAO_Inc" +
                            "identes", typeof(RecursoDAO_Incidentes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_descripcionbreve.
        /// </summary>
        internal static string i_descripcionbreve {
            get {
                return ResourceManager.GetString("i_descripcionbreve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_direccionincidente.
        /// </summary>
        internal static string i_direccionincidente {
            get {
                return ResourceManager.GetString("i_direccionincidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_estatus.
        /// </summary>
        internal static string i_estatus {
            get {
                return ResourceManager.GetString("i_estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fecha .
        /// </summary>
        internal static string i_fecha {
            get {
                return ResourceManager.GetString("i_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fechaatencion.
        /// </summary>
        internal static string i_fechaatencion {
            get {
                return ResourceManager.GetString("i_fechaatencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fechacompromiso.
        /// </summary>
        internal static string i_fechacompromiso {
            get {
                return ResourceManager.GetString("i_fechacompromiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fechafinservicio.
        /// </summary>
        internal static string i_fechafinservicio {
            get {
                return ResourceManager.GetString("i_fechafinservicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fecharequerida.
        /// </summary>
        internal static string i_fecharequerida {
            get {
                return ResourceManager.GetString("i_fecharequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fk_aliado.
        /// </summary>
        internal static string i_fk_aliado {
            get {
                return ResourceManager.GetString("i_fk_aliado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fk_cliente.
        /// </summary>
        internal static string i_fk_cliente {
            get {
                return ResourceManager.GetString("i_fk_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fk_contrato .
        /// </summary>
        internal static string i_fk_contrato {
            get {
                return ResourceManager.GetString("i_fk_contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fk_empleado.
        /// </summary>
        internal static string i_fk_empleado {
            get {
                return ResourceManager.GetString("i_fk_empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fk_equipo.
        /// </summary>
        internal static string i_fk_equipo {
            get {
                return ResourceManager.GetString("i_fk_equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fk_personal_contacto1.
        /// </summary>
        internal static string i_fk_personal_contacto1 {
            get {
                return ResourceManager.GetString("i_fk_personal_contacto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fk_personal_contacto2.
        /// </summary>
        internal static string i_fk_personal_contacto2 {
            get {
                return ResourceManager.GetString("i_fk_personal_contacto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_fk_servicio.
        /// </summary>
        internal static string i_fk_servicio {
            get {
                return ResourceManager.GetString("i_fk_servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_id.
        /// </summary>
        internal static string i_id {
            get {
                return ResourceManager.GetString("i_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_impacto.
        /// </summary>
        internal static string i_impacto {
            get {
                return ResourceManager.GetString("i_impacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_tiposervicio.
        /// </summary>
        internal static string i_tiposervicio {
            get {
                return ResourceManager.GetString("i_tiposervicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @i_urgencia.
        /// </summary>
        internal static string i_urgencia {
            get {
                return ResourceManager.GetString("i_urgencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_ALI_EST_IMP_URG.
        /// </summary>
        internal static string ProcedimientoActualizarAliEstImpUrg {
            get {
                return ResourceManager.GetString("ProcedimientoActualizarAliEstImpUrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_EMP_EST_IMP_URG.
        /// </summary>
        internal static string ProcedimientoActualizarEmpEstImpUrg {
            get {
                return ResourceManager.GetString("ProcedimientoActualizarEmpEstImpUrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_FECHA_ATENCION .
        /// </summary>
        internal static string ProcedimientoActualizarFechaAtencion {
            get {
                return ResourceManager.GetString("ProcedimientoActualizarFechaAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICAR_FECHA_CONCLUSION.
        /// </summary>
        internal static string ProcedimientoActualizarFechaConclusion {
            get {
                return ResourceManager.GetString("ProcedimientoActualizarFechaConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREGAR_INCIDENTE.
        /// </summary>
        internal static string ProcedimientoAgregarIncidente {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_FERIADOS.
        /// </summary>
        internal static string ProcedimientoConsultarFeriados {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_INCIDENTES_CLIENTE.
        /// </summary>
        internal static string ProcedimientoConsultarIncidentesPorCliente {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarIncidentesPorCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAR_INCIDENTES_TODOS.
        /// </summary>
        internal static string ProcedimientoConsultarIncidentesTodos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarIncidentesTodos", resourceCulture);
            }
        }
    }
}
